export const testProduct = {
	code: "04963406",
	product: {
		_id: "04963406",
		_keywords: [
			"soda",
			"sweetened",
			"coca",
			"coca-cola",
			"drink",
			"cola",
			"carbonated",
			"beverage",
		],
		added_countries_tags: [],
		additives_debug_tags: [],
		additives_n: 2,
		additives_old_n: 1,
		additives_old_tags: ["en:e150c"],
		additives_original_tags: ["en:e150c", "en:e338"],
		additives_prev_original_tags: ["en:e150a", "en:e338"],
		additives_tags: ["en:e150c", "en:e338"],
		additives_tags_n: null,
		allergens: "",
		allergens_from_ingredients: "",
		allergens_from_user: "(en) ",
		allergens_hierarchy: [],
		allergens_lc: "en",
		allergens_tags: [],
		amino_acids_prev_tags: [],
		amino_acids_tags: [],
		brands: "Coca Cola",
		brands_tags: ["coca-cola"],
		categories:
			"Beverages, Carbonated drinks, Sodas, Colas, Sweetened beverages",
		categories_hierarchy: [
			"en:beverages",
			"en:carbonated-drinks",
			"en:sodas",
			"en:colas",
			"en:sweetened-beverages",
		],
		categories_lc: "en",
		categories_old:
			"Beverages, Carbonated drinks, Sodas, Colas, Sweetened beverages",
		categories_properties: {
			"agribalyse_proxy_food_code:en": "18018",
			"ciqual_food_code:en": "18063",
		},
		categories_properties_tags: [
			"all-products",
			"categories-known",
			"agribalyse-food-code-unknown",
			"agribalyse-proxy-food-code-18018",
			"agribalyse-proxy-food-code-known",
			"ciqual-food-code-18063",
			"ciqual-food-code-known",
			"agribalyse-known",
			"agribalyse-18018",
		],
		categories_tags: [
			"en:beverages",
			"en:carbonated-drinks",
			"en:sodas",
			"en:colas",
			"en:sweetened-beverages",
		],
		category_properties: {
			"ciqual_food_name:en":
				"Cola, sugar and sweetener-s- content -average-",
			"ciqual_food_name:fr":
				"Cola, teneur en sucre et édulcorant inconnue -aliment moyen-",
		},
		checkers_tags: [],
		ciqual_food_name_tags: ["cola-sugar-and-sweetener-s-content-average"],
		cities_tags: [],
		code: "04963406",
		codes_tags: [
			"code-8",
			"04963xxx",
			"0496xxxx",
			"049xxxxx",
			"04xxxxxx",
			"0xxxxxxx",
		],
		compared_to_category: "en:sweetened-beverages",
		complete: 0,
		completeness: 0.7875,
		correctors_tags: [
			"tacinte",
			"alexfloresveliz",
			"cc0000",
			"inf",
			"bredowmax",
		],
		countries: "United States",
		countries_hierarchy: ["en:united-states"],
		countries_lc: "en",
		countries_tags: ["en:united-states"],
		created_t: 1375384688,
		creator: "openfoodfacts-contributors",
		data_quality_bugs_tags: [],
		data_quality_errors_tags: [],
		data_quality_info_tags: [
			"en:packaging-data-incomplete",
			"en:ingredients-percent-analysis-ok",
		],
		data_quality_tags: [
			"en:packaging-data-incomplete",
			"en:ingredients-percent-analysis-ok",
			"en:ingredients-en-ending-comma",
			"en:nutrition-value-under-0-1-g-salt",
		],
		data_quality_warnings_tags: [
			"en:ingredients-en-ending-comma",
			"en:nutrition-value-under-0-1-g-salt",
		],
		debug_param_sorted_langs: ["en"],
		ecoscore_data: {
			adjustments: {},
			ecoscore_not_applicable_for_category: "en:sodas",
			status: "unknown",
		},
		ecoscore_grade: "not-applicable",
		ecoscore_tags: ["not-applicable"],
		editors: ["", "tacinte", "stephane"],
		editors_tags: [
			"inf",
			"tacinte",
			"openfoodfacts-contributors",
			"alexfloresveliz",
			"cc0000",
			"bredowmax",
			"stephane",
		],
		emb_codes: "",
		emb_codes_20141016: "",
		emb_codes_orig: "",
		emb_codes_tags: [],
		entry_dates_tags: ["2013-08-01", "2013-08", "2013"],
		expiration_date: "",
		"fruits-vegetables-nuts_100g_estimate": 0,
		generic_name: "",
		generic_name_en: "",
		id: "04963406",
		image_front_small_url:
			"https://images.openfoodfacts.org/images/products/04963406/front_en.21.200.jpg",
		image_front_thumb_url:
			"https://images.openfoodfacts.org/images/products/04963406/front_en.21.100.jpg",
		image_front_url:
			"https://images.openfoodfacts.org/images/products/04963406/front_en.21.400.jpg",
		image_ingredients_small_url:
			"https://images.openfoodfacts.org/images/products/04963406/ingredients_en.32.200.jpg",
		image_ingredients_thumb_url:
			"https://images.openfoodfacts.org/images/products/04963406/ingredients_en.32.100.jpg",
		image_ingredients_url:
			"https://images.openfoodfacts.org/images/products/04963406/ingredients_en.32.400.jpg",
		image_nutrition_small_url:
			"https://images.openfoodfacts.org/images/products/04963406/nutrition_en.35.200.jpg",
		image_nutrition_thumb_url:
			"https://images.openfoodfacts.org/images/products/04963406/nutrition_en.35.100.jpg",
		image_nutrition_url:
			"https://images.openfoodfacts.org/images/products/04963406/nutrition_en.35.400.jpg",
		image_small_url:
			"https://images.openfoodfacts.org/images/products/04963406/front_en.21.200.jpg",
		image_thumb_url:
			"https://images.openfoodfacts.org/images/products/04963406/front_en.21.100.jpg",
		image_url:
			"https://images.openfoodfacts.org/images/products/04963406/front_en.21.400.jpg",
		images: {
			1: {
				sizes: {
					100: {
						h: 100,
						w: 75,
					},
					400: {
						h: 400,
						w: 300,
					},
					full: {
						h: 3264,
						w: 2448,
					},
				},
				uploaded_t: 1375384725,
				uploader: "openfoodfacts-contributors",
			},
			2: {
				sizes: {
					100: {
						h: 100,
						w: 74,
					},
					400: {
						h: 400,
						w: 297,
					},
					full: {
						h: 4208,
						w: 3120,
					},
				},
				uploaded_t: 1421397406,
				uploader: "tacinte",
			},
			3: {
				sizes: {
					100: {
						h: 100,
						w: 74,
					},
					400: {
						h: 400,
						w: 297,
					},
					full: {
						h: 4208,
						w: 3120,
					},
				},
				uploaded_t: 1421397412,
				uploader: "tacinte",
			},
			4: {
				sizes: {
					100: {
						h: 100,
						w: 74,
					},
					400: {
						h: 400,
						w: 297,
					},
					full: {
						h: 4208,
						w: 3120,
					},
				},
				uploaded_t: 1421397413,
				uploader: "tacinte",
			},
			5: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 2448,
						w: 3264,
					},
				},
				uploaded_t: "1374776967",
				uploader: "stephane",
			},
			6: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 2448,
						w: 3264,
					},
				},
				uploaded_t: "1374776970",
				uploader: "stephane",
			},
			7: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 2448,
						w: 3264,
					},
				},
				uploaded_t: "1374776974",
				uploader: "stephane",
			},
			8: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 2448,
						w: 3264,
					},
				},
				uploaded_t: "1374776980",
				uploader: "stephane",
			},
			9: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 2448,
						w: 3264,
					},
				},
				uploaded_t: "1374776984",
				uploader: "stephane",
			},
			10: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 2448,
						w: 3264,
					},
				},
				uploaded_t: "1374776998",
				uploader: "stephane",
			},
			11: {
				sizes: {
					100: {
						h: 100,
						w: 58,
					},
					400: {
						h: 400,
						w: 233,
					},
					full: {
						h: 516,
						w: 300,
					},
				},
				uploaded_t: "1478331702",
				uploader: "alexfloresveliz",
			},
			12: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 3024,
						w: 4032,
					},
				},
				uploaded_t: 1579389977,
				uploader: "bredowmax",
			},
			13: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 3024,
						w: 4032,
					},
				},
				uploaded_t: 1579389984,
				uploader: "bredowmax",
			},
			14: {
				sizes: {
					100: {
						h: 75,
						w: 100,
					},
					400: {
						h: 300,
						w: 400,
					},
					full: {
						h: 3024,
						w: 4032,
					},
				},
				uploaded_t: 1579389989,
				uploader: "bredowmax",
			},
			15: {
				sizes: {
					100: {
						h: 100,
						w: 75,
					},
					400: {
						h: 400,
						w: 300,
					},
					full: {
						h: 4032,
						w: 3024,
					},
				},
				uploaded_t: 1579389992,
				uploader: "bredowmax",
			},
			16: {
				sizes: {
					100: {
						h: 100,
						w: 75,
					},
					400: {
						h: 400,
						w: 300,
					},
					full: {
						h: 4032,
						w: 3024,
					},
				},
				uploaded_t: 1579389995,
				uploader: "bredowmax",
			},
			17: {
				sizes: {
					100: {
						h: 100,
						w: 75,
					},
					400: {
						h: 400,
						w: 300,
					},
					full: {
						h: 4032,
						w: 3024,
					},
				},
				uploaded_t: 1579389999,
				uploader: "bredowmax",
			},
			front: {
				geometry: "2027x3819-546-94",
				imgid: "2",
				normalize: null,
				rev: "8",
				sizes: {
					100: {
						h: 100,
						w: 53,
					},
					200: {
						h: 200,
						w: 106,
					},
					400: {
						h: 400,
						w: 212,
					},
					full: {
						h: 3819,
						w: 2027,
					},
				},
				white_magic: null,
			},
			front_en: {
				angle: "0",
				geometry: "0x0-0-0",
				imgid: "11",
				normalize: "false",
				rev: "21",
				sizes: {
					100: {
						h: 100,
						w: 58,
					},
					200: {
						h: 200,
						w: 116,
					},
					400: {
						h: 400,
						w: 233,
					},
					full: {
						h: 516,
						w: 300,
					},
				},
				white_magic: "false",
				x1: "0",
				x2: "0",
				y1: "0",
				y2: "0",
			},
			ingredients: {
				geometry: "1355x473-777-2377",
				imgid: "3",
				normalize: null,
				rev: "10",
				sizes: {
					100: {
						h: 35,
						w: 100,
					},
					200: {
						h: 70,
						w: 200,
					},
					400: {
						h: 140,
						w: 400,
					},
					full: {
						h: 473,
						w: 1355,
					},
				},
				white_magic: null,
			},
			ingredients_en: {
				angle: "0",
				geometry: "3516x323-173-1135",
				imgid: "12",
				normalize: "false",
				rev: "32",
				sizes: {
					100: {
						h: 9,
						w: 100,
					},
					200: {
						h: 18,
						w: 200,
					},
					400: {
						h: 37,
						w: 400,
					},
					full: {
						h: 323,
						w: 3516,
					},
				},
				white_magic: "false",
				x1: "17.20703125",
				x2: "366.01953125",
				y1: "112.6328125",
				y2: "144.6875",
			},
			nutrition: {
				geometry: "1303x2325-798-147",
				imgid: "3",
				normalize: "checked",
				rev: "9",
				sizes: {
					100: {
						h: 100,
						w: 56,
					},
					200: {
						h: 200,
						w: 112,
					},
					400: {
						h: 400,
						w: 224,
					},
					full: {
						h: 2325,
						w: 1303,
					},
				},
				white_magic: null,
			},
			nutrition_en: {
				angle: "0",
				geometry: "878x1694-932-413",
				imgid: "16",
				normalize: "false",
				rev: "35",
				sizes: {
					100: {
						h: 100,
						w: 52,
					},
					200: {
						h: 200,
						w: 104,
					},
					400: {
						h: 400,
						w: 207,
					},
					full: {
						h: 1694,
						w: 878,
					},
				},
				white_magic: "false",
				x1: "92.4609375",
				x2: "179.578125",
				y1: "40.9921875",
				y2: "209.07421875",
			},
		},
		informers_tags: [
			"openfoodfacts-contributors",
			"tacinte",
			"stephane",
			"cc0000",
			"bredowmax",
		],
		ingredients: [
			{
				id: "en:carbonated-water",
				percent_estimate: 58.3333333333333,
				percent_max: 100,
				percent_min: 16.6666666666667,
				text: "carbonated water",
				vegan: "yes",
				vegetarian: "yes",
			},
			{
				id: "en:high-fructose-corn-syrup",
				percent_estimate: 20.8333333333333,
				percent_max: 50,
				percent_min: 0,
				text: "high fructose corn syrup",
				vegan: "yes",
				vegetarian: "yes",
			},
			{
				id: "en:e150a",
				percent_estimate: 10.4166666666667,
				percent_max: 33.3333333333333,
				percent_min: 0,
				text: "caramel color",
				vegan: "yes",
				vegetarian: "yes",
			},
			{
				id: "en:e338",
				percent_estimate: 5.20833333333333,
				percent_max: 25,
				percent_min: 0,
				text: "phosphoric acid",
				vegan: "yes",
				vegetarian: "yes",
			},
			{
				id: "en:natural-flavouring",
				percent_estimate: 2.60416666666666,
				percent_max: 20,
				percent_min: 0,
				text: "natural flavors",
				vegan: "maybe",
				vegetarian: "maybe",
			},
			{
				id: "en:caffeine",
				percent_estimate: 2.60416666666666,
				percent_max: 16.6666666666667,
				percent_min: 0,
				text: "caffeine",
				vegan: "yes",
				vegetarian: "yes",
			},
		],
		ingredients_analysis_tags: [
			"en:palm-oil-free",
			"en:maybe-vegan",
			"en:maybe-vegetarian",
		],
		ingredients_debug: [
			"Carbonated Water",
			",",
			null,
			null,
			null,
			" High Fructose Corn Syrup",
			",",
			null,
			null,
			null,
			" Caramel Color",
			",",
			null,
			null,
			null,
			" Phosphoric Acid",
			",",
			null,
			null,
			null,
			" ",
			":",
			":",
			null,
			null,
			" Natural Flavors ",
			":",
			":",
			null,
			null,
			" ",
			",",
			null,
			null,
			null,
			" Caffeine",
		],
		ingredients_from_or_that_may_be_from_palm_oil_n: 0,
		ingredients_from_palm_oil_n: 0,
		ingredients_from_palm_oil_tags: [],
		ingredients_hierarchy: [
			"en:carbonated-water",
			"en:water",
			"en:high-fructose-corn-syrup",
			"en:glucose",
			"en:fructose",
			"en:corn-syrup",
			"en:glucose-fructose-syrup",
			"en:e150a",
			"en:e338",
			"en:natural-flavouring",
			"en:flavouring",
			"en:caffeine",
		],
		ingredients_ids_debug: [
			"carbonated-water",
			"high-fructose-corn-syrup",
			"caramel-color",
			"phosphoric-acid",
			"natural-flavors",
			"caffeine",
		],
		ingredients_n: 6,
		ingredients_n_tags: ["6", "1-10"],
		ingredients_original_tags: [
			"en:carbonated-water",
			"en:high-fructose-corn-syrup",
			"en:e150a",
			"en:e338",
			"en:natural-flavouring",
			"en:caffeine",
		],
		ingredients_percent_analysis: 1,
		ingredients_tags: [
			"en:carbonated-water",
			"en:water",
			"en:high-fructose-corn-syrup",
			"en:glucose",
			"en:fructose",
			"en:corn-syrup",
			"en:glucose-fructose-syrup",
			"en:e150a",
			"en:e338",
			"en:natural-flavouring",
			"en:flavouring",
			"en:caffeine",
		],
		ingredients_text:
			"carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine,",
		ingredients_text_debug:
			"Carbonated Water, High Fructose Corn Syrup, Caramel Color, Phosphoric Acid, : Natural Flavors : , Caffeine",
		ingredients_text_en:
			"carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine,",
		ingredients_text_with_allergens:
			"carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine,",
		ingredients_text_with_allergens_en:
			"carbonated water, high fructose corn syrup, caramel color, phosphoric acid, natural flavors, caffeine,",
		ingredients_that_may_be_from_palm_oil_n: 0,
		ingredients_that_may_be_from_palm_oil_tags: [],
		interface_version_created: "20130323.jqm",
		interface_version_modified: "20150316.jqm2",
		known_ingredients_n: 12,
		labels: "",
		labels_hierarchy: [],
		labels_lc: "en",
		labels_tags: [],
		lang: "en",
		languages: {
			"en:english": 5,
		},
		languages_codes: {
			en: 5,
		},
		languages_hierarchy: ["en:english"],
		languages_tags: ["en:english", "en:1"],
		last_edit_dates_tags: ["2021-07-05", "2021-07", "2021"],
		last_editor: null,
		last_image_dates_tags: ["2020-01-19", "2020-01", "2020"],
		last_image_t: 1579390000,
		last_modified_by: null,
		last_modified_t: 1625479440,
		lc: "en",
		link: "",
		main_countries_tags: [],
		manufacturing_places: "",
		manufacturing_places_tags: [],
		max_imgid: "17",
		minerals_prev_tags: [],
		minerals_tags: [],
		misc_tags: [
			"en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients",
			"en:nutrition-all-nutriscore-values-known",
			"en:nutriscore-computed",
			"en:ecoscore-not-applicable",
			"en:ecoscore-not-computed",
		],
		new_additives_n: 1,
		no_nutrition_data: "",
		nova_group: 4,
		nova_group_debug:
			" -- categories/en:sodas : 3 -- additives/en:e150c : 4",
		nova_groups: "4",
		nova_groups_tags: ["en:4-ultra-processed-food-and-drink-products"],
		nucleotides_prev_tags: [],
		nucleotides_tags: [],
		nutrient_levels: {
			fat: "low",
			salt: "low",
			"saturated-fat": "low",
			sugars: "high",
		},
		nutrient_levels_tags: [
			"en:fat-in-low-quantity",
			"en:saturated-fat-in-low-quantity",
			"en:sugars-in-high-quantity",
			"en:salt-in-low-quantity",
		],
		nutriments: {
			carbohydrates: 39,
			carbohydrates_100g: 11,
			carbohydrates_serving: 39,
			carbohydrates_unit: "g",
			carbohydrates_value: 39,
			energy: 586,
			"energy-kcal": 140,
			"energy-kcal_100g": 39.4,
			"energy-kcal_serving": 140,
			"energy-kcal_unit": "kcal",
			"energy-kcal_value": 140,
			energy_100g: 165,
			energy_serving: 586,
			energy_unit: "kcal",
			energy_value: 140,
			fat: 0,
			fat_100g: 0,
			fat_serving: 0,
			fat_unit: "g",
			fat_value: 0,
			fiber: 0,
			fiber_100g: 0,
			fiber_serving: 0,
			fiber_unit: "g",
			fiber_value: 0,
			"fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
			"nova-group": 4,
			"nova-group_100g": 4,
			"nova-group_serving": 4,
			"nutrition-score-fr": 14,
			"nutrition-score-fr_100g": 14,
			proteins: 0,
			proteins_100g: 0,
			proteins_serving: 0,
			proteins_unit: "g",
			proteins_value: 0,
			salt: 0.1125,
			salt_100g: 0.0317,
			salt_serving: 0.1125,
			salt_unit: "mg",
			salt_value: 112.5,
			"saturated-fat": 0,
			"saturated-fat_100g": 0,
			"saturated-fat_serving": 0,
			"saturated-fat_unit": "g",
			"saturated-fat_value": 0,
			sodium: 0.045,
			sodium_100g: 0.0127,
			sodium_serving: 0.045,
			sodium_unit: "mg",
			sodium_value: 45,
			sugars: 39,
			sugars_100g: 11,
			sugars_serving: 39,
			sugars_unit: "g",
			sugars_value: 39,
		},
		nutriscore_data: {
			energy: 165,
			energy_points: 6,
			energy_value: 165,
			fiber: 0,
			fiber_points: 0,
			fiber_value: 0,
			fruits_vegetables_nuts_colza_walnut_olive_oils: 0,
			fruits_vegetables_nuts_colza_walnut_olive_oils_points: 0,
			fruits_vegetables_nuts_colza_walnut_olive_oils_value: 0,
			grade: "e",
			is_beverage: 1,
			is_cheese: 0,
			is_fat: 0,
			is_water: 0,
			negative_points: 14,
			positive_points: 0,
			proteins: 0,
			proteins_points: 0,
			proteins_value: 0,
			saturated_fat: 0,
			saturated_fat_points: 0,
			saturated_fat_ratio: 0,
			saturated_fat_ratio_points: 0,
			saturated_fat_ratio_value: 0,
			saturated_fat_value: 0,
			score: 14,
			sodium: 12.7,
			sodium_points: 0,
			sodium_value: 12.7,
			sugars: 11,
			sugars_points: 8,
			sugars_value: 11,
		},
		nutriscore_grade: "e",
		nutriscore_score: 14,
		nutriscore_score_opposite: -14,
		nutrition_data: "on",
		nutrition_data_per: "serving",
		nutrition_data_prepared: "",
		nutrition_data_prepared_per: "100g",
		nutrition_grade_fr: "e",
		nutrition_grades: "e",
		nutrition_grades_tags: ["e"],
		nutrition_score_beverage: 1,
		nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients: 1,
		nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value: 0,
		origins: "",
		origins_hierarchy: [],
		origins_lc: "en",
		origins_old: "",
		origins_tags: [],
		other_nutritional_substances_tags: [],
		packaging: "can - metal",
		packaging_tags: ["can-metal"],
		packagings: [
			{
				material: "en:metal",
				shape: "en:can",
			},
		],
		photographers_tags: [
			"openfoodfacts-contributors",
			"tacinte",
			"stephane",
			"alexfloresveliz",
			"bredowmax",
		],
		pnns_groups_1: "Beverages",
		pnns_groups_1_tags: ["beverages", "known"],
		pnns_groups_2: "Sweetened beverages",
		pnns_groups_2_tags: ["sweetened-beverages", "known"],
		popularity_key: 19950000033,
		popularity_tags: [
			"top-50000-scans-2019",
			"top-100000-scans-2019",
			"at-least-5-scans-2019",
			"at-least-10-scans-2019",
			"top-75-percent-scans-2019",
			"top-80-percent-scans-2019",
			"top-85-percent-scans-2019",
			"top-90-percent-scans-2019",
			"top-10-us-scans-2019",
			"top-50-us-scans-2019",
			"top-100-us-scans-2019",
			"top-500-us-scans-2019",
			"top-1000-us-scans-2019",
			"top-5000-us-scans-2019",
			"top-10000-us-scans-2019",
			"top-50000-us-scans-2019",
			"top-100000-us-scans-2019",
			"top-country-us-scans-2019",
			"at-least-5-us-scans-2019",
			"at-least-10-us-scans-2019",
			"top-50000-be-scans-2019",
			"top-100000-be-scans-2019",
			"top-50000-ch-scans-2019",
			"top-100000-ch-scans-2019",
			"top-5000-ca-scans-2019",
			"top-10000-ca-scans-2019",
			"top-50000-ca-scans-2019",
			"top-100000-ca-scans-2019",
			"top-50000-scans-2020",
			"top-100000-scans-2020",
			"at-least-5-scans-2020",
			"at-least-10-scans-2020",
			"top-75-percent-scans-2020",
			"top-80-percent-scans-2020",
			"top-85-percent-scans-2020",
			"top-90-percent-scans-2020",
			"top-10-us-scans-2020",
			"top-50-us-scans-2020",
			"top-100-us-scans-2020",
			"top-500-us-scans-2020",
			"top-1000-us-scans-2020",
			"top-5000-us-scans-2020",
			"top-10000-us-scans-2020",
			"top-50000-us-scans-2020",
			"top-100000-us-scans-2020",
			"top-country-us-scans-2020",
			"at-least-5-us-scans-2020",
			"at-least-10-us-scans-2020",
			"top-5000-mx-scans-2020",
			"top-10000-mx-scans-2020",
			"top-50000-mx-scans-2020",
			"top-100000-mx-scans-2020",
			"top-500-in-scans-2020",
			"top-1000-in-scans-2020",
			"top-5000-in-scans-2020",
			"top-10000-in-scans-2020",
			"top-50000-in-scans-2020",
			"top-100000-in-scans-2020",
			"top-50000-es-scans-2020",
			"top-100000-es-scans-2020",
			"top-500-pk-scans-2020",
			"top-1000-pk-scans-2020",
			"top-5000-pk-scans-2020",
			"top-10000-pk-scans-2020",
			"top-50000-pk-scans-2020",
			"top-100000-pk-scans-2020",
		],
		product_name: "Coca-Cola",
		product_name_en: "Coca-Cola",
		product_quantity: "360",
		purchase_places: "Chicago,Illinois,USA",
		purchase_places_tags: ["chicago", "illinois", "usa"],
		quantity: "12 fl oz (355 ml)",
		removed_countries_tags: [],
		rev: 42,
		scans_n: 51,
		selected_images: {
			front: {
				display: {
					en: "https://images.openfoodfacts.org/images/products/04963406/front_en.21.400.jpg",
				},
				small: {
					en: "https://images.openfoodfacts.org/images/products/04963406/front_en.21.200.jpg",
				},
				thumb: {
					en: "https://images.openfoodfacts.org/images/products/04963406/front_en.21.100.jpg",
				},
			},
			ingredients: {
				display: {
					en: "https://images.openfoodfacts.org/images/products/04963406/ingredients_en.32.400.jpg",
				},
				small: {
					en: "https://images.openfoodfacts.org/images/products/04963406/ingredients_en.32.200.jpg",
				},
				thumb: {
					en: "https://images.openfoodfacts.org/images/products/04963406/ingredients_en.32.100.jpg",
				},
			},
			nutrition: {
				display: {
					en: "https://images.openfoodfacts.org/images/products/04963406/nutrition_en.35.400.jpg",
				},
				small: {
					en: "https://images.openfoodfacts.org/images/products/04963406/nutrition_en.35.200.jpg",
				},
				thumb: {
					en: "https://images.openfoodfacts.org/images/products/04963406/nutrition_en.35.100.jpg",
				},
			},
		},
		serving_quantity: "355",
		serving_size: "355 ml",
		sortkey: 1580240420,
		states: "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:origins-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:packaging-photo-to-be-selected, en:nutrition-photo-selected, en:ingredients-photo-selected, en:front-photo-selected, en:photos-uploaded",
		states_hierarchy: [
			"en:to-be-completed",
			"en:nutrition-facts-completed",
			"en:ingredients-completed",
			"en:expiration-date-to-be-completed",
			"en:packaging-code-to-be-completed",
			"en:characteristics-to-be-completed",
			"en:origins-to-be-completed",
			"en:categories-completed",
			"en:brands-completed",
			"en:packaging-completed",
			"en:quantity-completed",
			"en:product-name-completed",
			"en:photos-to-be-validated",
			"en:packaging-photo-to-be-selected",
			"en:nutrition-photo-selected",
			"en:ingredients-photo-selected",
			"en:front-photo-selected",
			"en:photos-uploaded",
		],
		states_tags: [
			"en:to-be-completed",
			"en:nutrition-facts-completed",
			"en:ingredients-completed",
			"en:expiration-date-to-be-completed",
			"en:packaging-code-to-be-completed",
			"en:characteristics-to-be-completed",
			"en:origins-to-be-completed",
			"en:categories-completed",
			"en:brands-completed",
			"en:packaging-completed",
			"en:quantity-completed",
			"en:product-name-completed",
			"en:photos-to-be-validated",
			"en:packaging-photo-to-be-selected",
			"en:nutrition-photo-selected",
			"en:ingredients-photo-selected",
			"en:front-photo-selected",
			"en:photos-uploaded",
		],
		stores: "",
		stores_tags: [],
		traces: "",
		traces_from_ingredients: "",
		traces_from_user: "(en) ",
		traces_hierarchy: [],
		traces_lc: "en",
		traces_tags: [],
		unique_scans_n: 33,
		unknown_ingredients_n: 0,
		unknown_nutrients_tags: [],
		update_key: "eco",
		vitamins_prev_tags: [],
		vitamins_tags: [],
	},
	status: 1,
	status_verbose: "product found",
};
